### ISSUE TITLE
Error on exporting Insurgency: Sandstorm maps

### ISSUE THREAD

**Issue by DarkBlade909** [MinshuG/BlenderUmap2#10]
Full error log at bottom
![image](https://user-images.githubusercontent.com/52094720/236631294-5f77b1a0-025c-40cf-8da2-2666266ad8af.png)
![image](https://user-images.githubusercontent.com/52094720/236631357-b045bb00-417c-48b2-bb94-eea30b9fbc84.png)

[BlenderUmap-2023-05-06.log](https://github.com/MinshuG/BlenderUmap2/files/11412609/BlenderUmap-2023-05-06.log)

**Comment by MinshuG** [comment]
you are using an old version of BlenderUmap2

**Comment by DarkBlade909** [comment]
Sorry about that, I was trying on multiple versions. The problem persists both on master, and on better-materials branch.

![image](https://user-images.githubusercontent.com/52094720/236725650-a5803919-f718-4e73-823d-c66eda14d37c.png)
![image](https://user-images.githubusercontent.com/52094720/236725625-75d38788-391c-4834-838d-536c82bc1498.png)

[BlenderUmap-2023-05-07.log](https://github.com/MinshuG/BlenderUmap2/files/11417378/BlenderUmap-2023-05-07.log)

**Comment by SphinxRa40** [comment]
At least yours do some extracting/importing, got the same errors in blender line 387/51, can you help with the basics? it's confusing, 'Game Path' should be the game's Paks folder, and 'Package' is the .umap file, now this is for me the confusing part, the .umaps are IN the .pak, I have also extracted the .pak with unrealpak/qbms, etc, to select the .umap (I guess we must figure that out ourselves?!) still no matter what I choose for directories / folders /names of the xxx.umap (also followed your screenshot of blender) for the .log always mention xxxx.umap not found :/ or I don't understand the logic what to put that's fine also as long you can help me further :)

**Comment by DarkBlade909** [comment]
Latest Patreon release of Umap fixes this, thanks.
