### ISSUE TITLE
Import is completely corrupted when extracting from MediEvil (PS4)

### ISSUE THREAD

**Issue by ControVR** [MinshuG/BlenderUmap2#12]
Hi.

I'm importing the game MediEvil, specifically the PS4 remake, and everytime i've imported a map, it has come up with corrupted textures. I'll attach a screenshot of my file explorer to show said textures.
![Control-V (9)](https://github.com/MinshuG/BlenderUmap2/assets/73795347/7e95df17-e720-4b06-aaac-e0d44c2e35cf)

I've had this problem for a while, but never really needed to get it officially fixed, because i had another source with non-corrupted textures that i could replace the corrupted ones with. But it's quite the problem now that 11.6 has been released, and terrain being importable.

Now as i said before, the textures weren't that big of a deal, but now that terrain has been added as an importable thing, i wanted to import a new map which had terrain. Although it seems that it also corrupts in a way (Attached image of terrain below)
![Control-V (10)](https://github.com/MinshuG/BlenderUmap2/assets/73795347/6f6ec080-f6dc-478d-9ea5-4ada0c7cc0c6)

The thing is, umodel also had the corrupted texture problem, but you can fix that by switching the platform to PS4.
![medieviltexturefix](https://github.com/MinshuG/BlenderUmap2/assets/73795347/b139b257-ef7d-4836-8064-eca73f61373d)

So i was thinking, is there a way i can specify that the umap i'm importing is from a PS4 game? Maybe that could fix the terrain problem? 
I'd like to fix this problem as soon as possible, as i would like to use it for a Halloween thing i'm doing.

**Comment by MinshuG** [comment]
can you check if the textures work in FModel with platform set to PlayStation?

**Comment by ControVR** [comment]
Yes, it seems to also be loading them fine in FModel
![Control-V (11)](https://github.com/MinshuG/BlenderUmap2/assets/73795347/bd9ae8b4-baaf-4a4d-bd11-20326e95030a)

**Comment by MinshuG** [comment]
I’ll add Platform picker in next version.

**Comment by ControVR** [comment]
Many thanks 🙏
