### ISSUE TITLE
How to Use Mappings

### ISSUE THREAD

**Issue by DLDrago** [MinshuG/BlenderUmap2#13]
I'm wondering how to use mappings with the addon.

**Comment by MinshuG** [comment]
put the mappings file (.usmap) in the EXPORT_DIRECTORY/mappings folder. BlenderUmap will load the latest file ([ref](https://github.com/MinshuG/BlenderUmap2/blob/87ae84e70f706356945c8152a407108262a41897/BlenderUmap/BlenderUmap.cs#L133)) from there.

**Comment by DLDrago** [comment]
Ok, that seemed to work.  Now I have a new question.  What psk/psa plugin do I use?  I used the one from Blacklight Games and it threw an error that it couldn't find the 280 one.  I tried the 280 one and it had errors, but I was probably using an old one.

**Comment by DLDrago** [comment]
The error I'm getting is that it can't import pskimport.
