### ISSUE TITLE
Documentation for working with replay files

### ISSUE THREAD

**Issue by miked63017** [MinshuG/BlenderUmap2#16]
Is there any documentation, or if possible can you provide a brief rundown of how I could export actors from a replay file?

**Comment by MinshuG** [comment]
put path to replay file in package path

**Comment by miked63017** [comment]
Any advice on how to find the names of objects to import?

**Comment by MinshuG** [comment]
wdym by names of object? umaps/levels?

**Comment by miked63017** [comment]
Yeah, I haven't noticed a drop down box or anything. It seems like I need
to know the name/path of the asset, but I could be missing something.

**Comment by MinshuG** [comment]
Use FModel or UModel/UEViewer for getting package names
