### ISSUE TITLE
error when using make_release.py

### ISSUE THREAD

**Issue by jkerman2000** [MinshuG/BlenderUmap2#9]
I have successfully cloned the repo, but I cannot build the addon because if the following error:

  OozSharp -> C:\Users\XXX\BlenderUmap2\FortniteReplayDecompressor\src\OozSharp\bin\Release\net5.0\OozSharp.dll
  -- Configuring incomplete, errors occurred!
  CMake Error at CMakeLists.txt:2 (project):
    Running

     'nmake' '-?'

    failed with:

     The system cannot find the file specified

EXEC : CMake error : CMAKE_CXX_COMPILER not set, after EnableLanguage [C:\Users\XXX\BlenderUmap2\CUE4Parse\CUE4Parse\
CUE4Parse.csproj]
  See also "C:/Users/XXX/BlenderUmap2/CUE4Parse/CUE4Parse-Natives/builddir/CMakeFiles/CMakeOutput.log".
C:\Users\XXX\BlenderUmap2\CUE4Parse\CUE4Parse\CUE4Parse.csproj(51,5): error MSB3073: The command "cmake .." exited wi
th code 1.
  Unreal.Core -> C:\Users\XXX\BlenderUmap2\FortniteReplayDecompressor\src\Unreal.Core\bin\Release\net5.0\Unreal.Core.
  dll
  Unreal.Encryption -> C:\Users\XXX\BlenderUmap2\FortniteReplayDecompressor\src\Unreal.Encryption\bin\Release\net5.0\
  Unreal.Encryption.dll
  FortniteReplayReader -> C:\Users\XXX\BlenderUmap2\FortniteReplayDecompressor\src\FortniteReplayReader\bin\Release\n
  et5.0\FortniteReplayReader.dll

I've had similar issues when trying to compile other C++ projects, how do I force it to use the right compiler? At least, I think that's what the problem might be.

**Comment by MinshuG** [comment]
Install cpp workload in visual studio

**Comment by jkerman2000** [comment]
Tried that, still have the same error. I have no idea what I'm doing in the first place, could I be just making a dumb mistake?

**Comment by jkerman2000** [comment]
Do I have to manually add or remove anything in my PATH system variable?

**Comment by jkerman2000** [comment]
Okay, so I added both CMake and the path to NMake into my path variable after reinstalling both CMake and MinGW. Now I get this error:

The system cannot find the file specifiedNMAKE : fatal error U1077: '"C:\Program Files\CMake\bin\cmake.exe"' : return c
ode '0xffffffff' [C:\Users\XXX\BlenderUmap2\CUE4Parse\CUE4Parse\CUE4Parse.csproj]
      Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\bi
n\Hostx64\x64\nmake.exe"' : return code '0x2' [C:\Users\XXX\BlenderUmap2\CUE4Parse\CUE4Parse\CUE4Parse.csproj]
      Stop.





    CMake will not be able to correctly generate this project.
  Call Stack (most recent call first):
    CMakeLists.txt:2 (project)

**Comment by jkerman2000** [comment]
Okay, I figured out the problem: after re-cloning the repo, I had to change the langversion in CueParse to "preview" and that fixed it.
